site_name: Wirecard ePOS API
docs_dir: docs_source
site_dir: docs

theme:
  name: 'material'

markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_css:
  - 'stylesheets/minimal-epossdk.css'
extra_javascript:
  - 'javascript/external-links.js'

extra:
  logo: 'images/logo.svg'
  social:
    - type: 'github'
      link: 'https://github.com/WirecardMobileServices/Wirecard-ePOS-iOS/issues'
    - type: 'apple'
      link: 'https://github.com/WirecardMobileServices/Wirecard-ePOS-iOS'
    - type: 'android'
      link: 'https://github.com/WirecardMobileServices/Wirecard-ePOS-Android'
  palette:
    primary: 'indigo'
    accent: 'red'

# Page tree
nav:
  - Welcome: index.md
  - Start:
    - Introduction: start.md
    - Getting Started: auth.md
  - Core Integration:
    - Overview: sale.md
    - Sale Processing:
      - General: multitender.md
      - Payments:
        - Cash: cash.md
        - Card: card.md
        - AliPay: alipay.md
        - WeChat Pay: wechat.md
  - Advanced Integration:
    - Sale Items:
      - General: items.md
      - Discounts: discounts.md
    - User management: user.md
    - Product catalogue:
      - General: card.md
      - Catalogue hierarchy: card.md
      - Product item: card.md
    - Merchant management:
      - General: card.md
      - Shop management: card.md
    - Cash Register:
      - General: card.md
      - Cash registers: card.md
      - Shifts: card.md
    - Terminal management: card.md
  - Glossary: glossary.md