site_name: Wirecard ePOS
docs_dir: docs_source
site_dir: docs

theme:
  name: 'material'

markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_css:
  - 'stylesheets/minimal-epossdk.css'
extra_javascript:
  - 'javascript/external-links.js'

extra:
  logo: 'images/logo.svg'
  social:
    - type: 'github'
      link: 'https://github.com/WirecardMobileServices/Wirecard-ePOS-iOS/issues'
    - type: 'apple'
      link: 'https://github.com/WirecardMobileServices/Wirecard-ePOS-iOS'
    - type: 'android'
      link: 'https://github.com/WirecardMobileServices/Wirecard-ePOS-Android'
  palette:
    primary: 'indigo'
    accent: 'red'

# Page tree
nav:
  - Welcome: index.md
  - Start: start.md
    - Getting started: start.md
    - Security: auth.md
    - User management: user.md
  - Sale: sale.md
    - Getting started: sale.md
    - Multi-tender sale: multitender.md
    - Items: items.md
      - General: items.md
      - Discounts: discounts.md
    - Payments:
      - Cash: cash.md
      - Card: card.md
      - AliPay: alipay.md
      - WeChat Pay: wechat.md
  - Product catalogue:
   - Getting started:
   - Catalogue hierarchy:
   - Product item:
  - Merchant management:
    - Getting started:
    - Shop management:
  - Cash management:
   - Getting started:
   - Cash registers:
   - Shifts:
  - Terminal management:
  - Glossary: glossary.md
